Use pre-built notarized kexts if available
1. Uses tap-notarized.kext and tun-notarized.kext if they exist in the third_party folder. If they don't, then new tap and tun kexts are built.

2. Requires kexts to be named tap-notarized.kext and tun-notarized.kext.

3. Requires macOS 10.9 or higher.

REASONS:

1. macOS 10.14.5 will apparently require notarized kexts.

2.  It is impossible to create notarized kexts that will work on macOS 10.7 or 10.8 because macOS 10.7 and 10.8 cannot load kexts signed with the modern version of codesign that is required for kexts to be notarized.

3. Including notarized kexts allows rebranding of Tunnelblick and signing or notarizing the rebranded application with a regular Developer certificate, that is, it does not require a "kext signing" certificate.

diff --git a/third_party/makefiles/Makefile-tuntap b/third_party/makefiles/Makefile-tuntap
--- a/third_party/makefiles/Makefile-tuntap
+++ b/third_party/makefiles/Makefile-tuntap
@@ -19,53 +19,83 @@
 #  distribution); if not, write to the Free Software Foundation, Inc.,
 
 built-tuntap-prepare:
-	@echo "THIRD_PARTY: Expanding Tun/Tap ..."
-	cd $(TUNTAP_SOURCE_DIR)/$(TUNTAP_20111101_NAME) ; \
-    mkdir -p $(TUNTAP_BUILD_DIR)/$(TUNTAP_20111101_NAME) ; \
-	tar -x -f $(TUNTAP_20111101_TARGZ) -C $(TUNTAP_BUILD_DIR)/$(TUNTAP_20111101_NAME) ; \
-	cd $(TUNTAP_SOURCE_DIR)/$(TUNTAP_CURRENT_NAME) ; \
-    mkdir -p $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME) ; \
-	tar -x -f $(TUNTAP_CURRENT_TARGZ) -C $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME) ;
-	@echo "THIRD_PARTY: Patching Tun/Tap..."
-	for tuntapdir in $(TUNTAP_20111101_NAME) $(TUNTAP_CURRENT_NAME) ; do \
-		if [ -d $(TUNTAP_BUILD_DIR)/$$tuntapdir/tuntap ] ; then \
-			cd $(TUNTAP_BUILD_DIR)/$$tuntapdir/tuntap ; \
-			for patch_file in $(TUNTAP_SOURCE_DIR)/$$tuntapdir/patches/*.diff; do \
-				patch_name=$$tuntapdir/$$(basename "$${patch_file}") ; \
-				patch -p0 -N --dry-run -i $$patch_file > /dev/null; \
-				if [ $$? == 0 ]; then \
-					patch -p0 -N -i $$patch_file; \
+	if [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] \
+	&& [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
+		echo "THIRD_PARTY: Not expanding or patching Tun/Tap because pre-built kexts exist" ; \
+	elif [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] \
+	  || [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
+		echo "error: THIRD_PARTY: If either tap-notarized.kext or tun-notarized.kext is present in the third_party folder, both must be present" ; \
+		exit 1 ; \
+	else \
+		echo "THIRD_PARTY: Expanding Tun/Tap ..." ; \
+		cd $(TUNTAP_SOURCE_DIR)/$(TUNTAP_20111101_NAME) ; \
+		mkdir -p $(TUNTAP_BUILD_DIR)/$(TUNTAP_20111101_NAME) ; \
+		tar -x -f $(TUNTAP_20111101_TARGZ) -C $(TUNTAP_BUILD_DIR)/$(TUNTAP_20111101_NAME) ; \
+		cd $(TUNTAP_SOURCE_DIR)/$(TUNTAP_CURRENT_NAME) ; \
+		mkdir -p $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME) ; \
+		tar -x -f $(TUNTAP_CURRENT_TARGZ) -C $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME) ; \
+		echo "THIRD_PARTY: Patching Tun/Tap.." ; \
+		for tuntapdir in $(TUNTAP_20111101_NAME) $(TUNTAP_CURRENT_NAME) ; do \
+			if [ -d $(TUNTAP_BUILD_DIR)/$$tuntapdir/tuntap ] ; then \
+				cd $(TUNTAP_BUILD_DIR)/$$tuntapdir/tuntap ; \
+				for patch_file in $(TUNTAP_SOURCE_DIR)/$$tuntapdir/patches/*.diff; do \
+					patch_name=$$tuntapdir/$$(basename "$${patch_file}") ; \
+					patch -p0 -N --dry-run -i $$patch_file > /dev/null; \
 					if [ $$? == 0 ]; then \
-						echo "Tun/Tap patch applied: $$patch_name" ; \
+						patch -p0 -N -i $$patch_file; \
+						if [ $$? == 0 ]; then \
+							echo "Tun/Tap patch applied: $$patch_name" ; \
+						else \
+							echo "error: Tun/Tap patch failed after a successful dry run: $$patch_name" ; \
+						fi \
 					else \
-						echo "error: Tun/Tap patch failed after a successful dry run: $$patch_name" ; \
+						echo "error: Tun/Tap patch could not be applied: $$patch_name" ; \
 					fi \
-				else \
-					echo "error: Tun/Tap patch could not be applied: $$patch_name" ; \
-				fi \
-			done ; \
-		fi ; \
-	done
+				done ; \
+			fi ; \
+		done ; \
+		echo "THIRD_PARTY: Patched Tun/Tap" ; \
+	fi
 	touch built-tuntap-prepare
-	@echo "THIRD_PARTY: Patched Tun/Tap"
 
 built-tuntap: built-tuntap-prepare
-	@echo "THIRD_PARTY: Building Tun/Tap for '$(ARCHS)' with deploy-target '$(MACOSX_DEPLOYMENT_TARGET)' and SDK path '$(SDK_DIR)'" ;
-	export TUNTAP_ARCHS="$(foreach f, $(TARGET_ARCHS), -arch $f)" ; \
-	cd $(TUNTAP_BUILD_DIR) ; \
-	mkdir -p $(TUNTAP_PRODUCTS_DIR) ; \
-	$(MAKE) -C $(TUNTAP_20111101_NAME)/tuntap/ ; \
-	cp -f -p -R $(TUNTAP_20111101_NAME)/tuntap/tap.kext $(TUNTAP_PRODUCTS_DIR)/tap-20111101.kext ; \
-	cp -f -p -R $(TUNTAP_20111101_NAME)/tuntap/tun.kext $(TUNTAP_PRODUCTS_DIR)/tun-20111101.kext ; \
-	$(MAKE) -C $(TUNTAP_CURRENT_NAME)/tuntap/ ; \
-	cp -f -p -R $(TUNTAP_CURRENT_NAME)/tuntap/tap.kext $(TUNTAP_PRODUCTS_DIR)/tap.kext ; \
-	cp -f -p -R $(TUNTAP_CURRENT_NAME)/tuntap/tun.kext $(TUNTAP_PRODUCTS_DIR)/tun.kext
+	if [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] \
+	&& [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
+		echo "THIRD_PARTY: Not building Tun/Tap because pre-built kexts exist" ; \
+		mkdir -p $(TUNTAP_PRODUCTS_DIR) ; \
+		cp -f -a $(TUNTAP_PREBUILT_TAP_NOTARIZED) $(TUNTAP_PRODUCTS_DIR)/tap-notarized.kext ; \
+		cp -f -a $(TUNTAP_PREBUILT_TUN_NOTARIZED) $(TUNTAP_PRODUCTS_DIR)/tun-notarized.kext ; \
+	elif [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] \
+	||   [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
+		echo "error: THIRD_PARTY: If either tap-notarized.kext or tun-notarized.kext is present in the third_party folder, both must be present" ; \
+		exit 1 ; \
+	else \
+		echo "THIRD_PARTY: Building Tun/Tap for '$(ARCHS)' with deploy-target '$(MACOSX_DEPLOYMENT_TARGET)' and SDK path '$(SDK_DIR)'" ; \
+		export TUNTAP_ARCHS="$(foreach f, $(TARGET_ARCHS), -arch $f)" ; \
+		cd $(TUNTAP_BUILD_DIR) ; \
+		mkdir -p $(TUNTAP_PRODUCTS_DIR) ; \
+		$(MAKE) -C $(TUNTAP_20111101_NAME)/tuntap/ ; \
+		cp -f -p -R $(TUNTAP_20111101_NAME)/tuntap/tap.kext $(TUNTAP_PRODUCTS_DIR)/tap-20111101.kext ; \
+		cp -f -p -R $(TUNTAP_20111101_NAME)/tuntap/tun.kext $(TUNTAP_PRODUCTS_DIR)/tun-20111101.kext ; \
+		$(MAKE) -C $(TUNTAP_CURRENT_NAME)/tuntap/ ; \
+		cp -f -a $(TUNTAP_CURRENT_NAME)/tuntap/tap.kext $(TUNTAP_PRODUCTS_DIR)/tap.kext ; \
+		cp -f -a $(TUNTAP_CURRENT_NAME)/tuntap/tun.kext $(TUNTAP_PRODUCTS_DIR)/tun.kext ; \
+		echo "THIRD_PARTY: Built Tun/Tap" ; \
+	fi ; \
 	touch built-tuntap
-	@echo "THIRD_PARTY: Built Tun/Tap"
 
 built-tuntap-clean:
-	@echo "THIRD_PARTY: Cleaning Tun/Tap..."
-	rm -f -R $(TUNTAP_BUILD_DIR)
-	rm -f -R $(TUNTAP_PRODUCTS_DIR)
-	rm -f built-tuntap
-	@echo "THIRD_PARTY: Cleaned Tun/Tap"
+	if [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] \
+	&& [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
+		echo "THIRD_PARTY: Not cleaning Tun/Tap because pre-built kexts exist" ; \
+	elif [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] \
+	||   [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
+		echo "error: THIRD_PARTY: If either tap-notarized.kext or tun-notarized.kext is present in the third_party folder, both must be present" ; \
+		exit 1 ; \
+	else \
+		echo "THIRD_PARTY: Cleaning Tun/Tap..." ; \
+		rm -f -R $(TUNTAP_BUILD_DIR) ; \
+		rm -f -R $(TUNTAP_PRODUCTS_DIR) ; \
+		rm -f built-tuntap ; \
+		echo "THIRD_PARTY: Cleaned Tun/Tap" ; \
+	fi
