Make almost all third-party binaries for arm64 and x86_64
Exception: OpenVPN 2.3.18 with OpenSSL 1.0 because OpenSSL 1.0 doesn't build with arm64. (OpenVPN 2.3.18 with LibreSSL is built for both arm64 and x86-64.

diff --git a/third_party/makefiles/Makefile-allssl b/third_party/makefiles/Makefile-allssl
--- a/third_party/makefiles/Makefile-allssl
+++ b/third_party/makefiles/Makefile-allssl
@@ -1,7 +1,7 @@
 # Makefile to build (Open|Libre)SSL for Tunnelblick
 #
 # Copyright 2004, 2005, 2006, 2007, 2008, 2009 Angelo Laub
-# Contributions by Jonathan K. Bullard Copyright 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018, 2020. All rights reserved.
+# Contributions by Jonathan K. Bullard Copyright 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018, 2020, 2021. All rights reserved.
 #
 #  This file is part of Tunnelblick.
 #
@@ -67,64 +67,52 @@ built-allssl: built-allssl-prepare
 			exit 255 ; \
 		fi ; \
 		for a in $${buildarch}; do \
+			if [ "$${sslvariant:0:7}" = "openssl" ] ; then \
+				if [ "$$a" = "$(TB_COMMON_X86_ARCH)" ] ; then \
+					ssl_arch="$(TB_OPENSSL_X86_ARCH)" ; \
+				elif [ "$$a" = "$(TB_COMMON_ARM_ARCH)" ] ; then \
+					ssl_arch="$(TB_OPENSSL_ARM_ARCH)" ; \
+				else \
+					echo "error: Unknown architecture '$$a' cannot be translated to a triple for building OpenSSL" ; \
+					exit 255; \
+				fi ; \
+			fi; \
+            if [ "$${a:0:3}" = "arm" ] ; then \
+                TB_CONFIGURE_BUILD="arm-apple-darwin" ; \
+            else \
+                TB_CONFIGURE_BUILD="$$a-apple-darwin" ; \
+            fi ; \
 			cd $${ssldir}; \
-			a=$${a#\"*}; \
-			a=$${a%*\"}; \
-			echo "Clean $${sslversion} for $$a" ; \
+			staging="$(STAGING_DIR)/$${sslversion}_$$a"; \
+			echo "Clean $${sslversion} for $$a ($$ssl_arch)" ; \
 			$(MAKE) clean; \
-			echo "Make $${sslversion} for $$a" ; \
-			echo "PREFIX: $(STAGING_DIR)/$${sslversion}/$${a}"; \
+			echo "Make $${sslversion} for $$a ($$ssl_arch)" ; \
 			echo "CC: $(CC)"; \
 			echo "CFLAGS: $(CFLAGS)"; \
 			if [ "$${sslversion}" = "$(OPENSSL_1_0_NAME)" ] ; then \
-				CC=$(CC) CFLAGS="$(CFLAGS)" ./Configure no-shared zlib no-zlib-dynamic no-asm no-krb5 --prefix="$(STAGING_DIR)/$${sslversion}/$$a" $$a; \
+				CC=$(CC) CFLAGS="$(CFLAGS) -arch $$a" ./Configure no-shared zlib no-zlib-dynamic no-asm no-krb5 --prefix="$$staging" $$ssl_arch; \
 				$(MAKE) build_libs build_apps openssl.pc libssl.pc libcrypto.pc; \
-				echo "Install to $(STAGING_DIR)/$${sslversion}/$$a" ; \
+				echo "Install $${sslversion} for $$a to $$staging" ; \
 				$(MAKE) install_sw; \
 			elif [ "$${sslversion}" = "$(OPENSSL_1_1_NAME)" ] ; then \
-				CC=$(CC) CFLAGS="$(CFLAGS)" ./Configure no-shared zlib no-asm --openssldir="$(STAGING_DIR)/$${sslversion}/$$a" $$a; \
+				CC=$(CC) CFLAGS="$(CFLAGS) -arch $$a" ./Configure no-shared zlib no-asm --openssldir="$$staging" $$ssl_arch; \
 				$(MAKE) build_libs build_apps openssl.pc libssl.pc libcrypto.pc; \
-				echo "Install to $(STAGING_DIR)/$${sslversion}/$$a" ; \
-				$(MAKE) DESTDIR="$(STAGING_DIR)/$${sslversion}/$$a" install_sw; \
-				mv "$(STAGING_DIR)/$${sslversion}/$$a/usr/local/bin" "$(STAGING_DIR)/$${sslversion}/$$a/bin" ;\
-				mv "$(STAGING_DIR)/$${sslversion}/$$a/usr/local/lib" "$(STAGING_DIR)/$${sslversion}/$$a/lib" ; \
-				mv "$(STAGING_DIR)/$${sslversion}/$$a/usr/local/include" "$(STAGING_DIR)/$${sslversion}/$$a/include" ; \
-				rm -f -r "$(STAGING_DIR)/$${sslversion}/$$a/usr" ; \
+				echo "Install $${sslversion} for $$a to $$staging" ; \
+				$(MAKE) DESTDIR="$$staging" install_sw; \
+				mv "$$staging/usr/local/bin"     "$$staging/bin" ;\
+				mv "$$staging/usr/local/lib"     "$$staging/lib" ; \
+				mv "$$staging/usr/local/include" "$$staging/include" ; \
+				rm -fr "$$staging/usr" ; \
 			elif [ "$${sslversion}" = "$(LIBRESSL_NAME)" ] ; then \
-				CC=$(CC) CFLAGS="$(CFLAGS)" ./configure --disable-shared --disable-asm --prefix="$(STAGING_DIR)/$${sslversion}/$$a" $$a; \
+				CC=$(CC) CFLAGS="$(CFLAGS) -arch $$a" ./configure --disable-shared --disable-asm --prefix="$$staging" --build="$$TB_CONFIGURE_BUILD" --host="$(TB_CONFIGURE_HOST)" $$ssl_arch; \
 				$(MAKE) check; \
-				echo "Install to $(STAGING_DIR)/$${sslversion}/$$a" ; \
+				echo "Install $${sslversion} for $$a to $$staging" ; \
 				$(MAKE) install; \
 			else \
 				echo "error: do not know how to build '$${sslvariant}' ($${sslversion})" ; \
 			fi ; \
 			cd .. ; \
 		done ; \
-		if [ -e "$(STAGING_DIR)/$${sslversion}/darwin64-x86_64-cc" ] ; then \
-			mv "$(STAGING_DIR)/$${sslversion}/darwin64-x86_64-cc" "$(STAGING_DIR)/$${sslversion}/x86_64" ; \
-		fi ; \
-		if [ -e "$(STAGING_DIR)/$${sslversion}/darwin64-arm64-cc" ] ; then \
-			mv "$(STAGING_DIR)/$${sslversion}/darwin64-arm64-cc" "$(STAGING_DIR)/$${sslversion}/arm64" ; \
-		fi ; \
-		mkdir -p "$(STAGING_DIR)/$${sslversion}/lib" ; \
-		if [ "$${sslversion}" = "$(OPENSSL_1_0_NAME)" ] ; then \
-			for t in $(OPENSSL_1_0_TARGET_FILES); do \
-				lipo $(STAGING_DIR)/$${sslversion}/*/lib/$$(basename $$t) -create -output $$t; \
-				ranlib $$t; \
-			done ; \
-		elif [ "$${sslversion}" = "$(OPENSSL_1_1_NAME)" ] ; then \
-			for t in $(OPENSSL_1_1_TARGET_FILES); do \
-				lipo $(STAGING_DIR)/$${sslversion}/*/lib/$$(basename $$t) -create -output $$t; \
-				ranlib $$t; \
-			done ; \
-		elif [ "$${sslversion}" = "$(LIBRESSL_NAME)" ] ; then \
-			for t in $(LIBRESSL_TARGET_FILES); do \
-				lipo $(STAGING_DIR)/$${sslversion}/*/lib/$$(basename $$t) -create -output $$t; \
-				ranlib $$t; \
-			done ; \
-		else \
-			echo "error: do not know how to lipo '$${sslvariant}' ($${sslversion})" ; \
-		fi ; \
 	done
 	cd $(TOPDIR)
 	touch built-allssl
diff --git a/third_party/makefiles/Makefile-openvpn b/third_party/makefiles/Makefile-openvpn
--- a/third_party/makefiles/Makefile-openvpn
+++ b/third_party/makefiles/Makefile-openvpn
@@ -1,7 +1,7 @@
 # Makefile to build openvpn for Tunnelblick
 #
 # Copyright 2004, 2005, 2006, 2007, 2008, 2009 Angelo Laub
-# Contributions by Jonathan K. Bullard Copyright 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2020. All rights reserved.
+# Contributions by Jonathan K. Bullard Copyright 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2020, 2021. All rights reserved.
 #
 #  This file is part of Tunnelblick.
 #
@@ -23,10 +23,6 @@ built-openvpn-prepare:
 	mkdir -p $(OPENVPN_BUILD_DIR)
 	cd "$(SOURCES_DIR)" ; \
 	for openvpn_folder_name in $$(ls openvpn) ; do \
-        if [ "$${openvpn_folder_name:0:11}" = "openvpn-2.3" ] && [ "$(OPENVPN_OPENSSL_1_1_TARGET_ARCHS)" = "arm64" ] ; then \
-            echo "THIRD_PARTY: SKIP openvpn-2.3 for arm64"; \
-            continue; \
-        fi ; \
 		cd "$(OPENVPN_SOURCE_DIR)/$$openvpn_folder_name" ; \
 		openvpn_tar_gz_name=$$(ls openvpn*.tar.?z) ; \
 		cd ../../ ; \
@@ -92,137 +88,137 @@ built-openvpn: built-openvpn-prepare built-lzo built-lz4 built-pkcs11-helper bui
                 fi ; \
                 if [ "$$ssl_name" = "$(OPENSSL_1_0_NAME)" ] ; then \
                     ssl_staging_dir="$(OPENSSL_1_0_STAGING_DIR)" ; \
-                    ssl_target_files="$(OPENSSL_1_0_TARGET_FILES)" ; \
-		    target_archs="$(OPENVPN_OPENSSL_1_0_TARGET_ARCHS)" ; \
+                    target_archs="$(OPENVPN_OPENSSL_1_0_TARGET_ARCHS)" ; \
                     pkcs11_enable="" ; \
                 elif [ "$$ssl_name" = "$(OPENSSL_1_1_NAME)" ] ; then \
                     ssl_staging_dir="$(OPENSSL_1_1_STAGING_DIR)" ; \
-                    ssl_target_files="$(OPENSSL_1_1_TARGET_FILES)" ; \
-		    target_archs="$(OPENVPN_OPENSSL_1_1_TARGET_ARCHS)" ; \
+                    target_archs="$(OPENVPN_OPENSSL_1_1_TARGET_ARCHS)" ; \
                     pkcs11_enable="--enable-pkcs11" ; \
                 elif [ "$$ssl_name" = "$(LIBRESSL_NAME)"    ] ; then \
                     ssl_staging_dir="$(LIBRESSL_STAGING_DIR)" ; \
-                    ssl_target_files="$(OPENSSL_1_0_TARGET_FILES)" ; \
-		    target_archs="$(OPENVPN_LIBRESSL_TARGET_ARCHS)" ; \
+                    target_archs="$(OPENVPN_LIBRESSL_TARGET_ARCHS)" ; \
                     pkcs11_enable="" ; \
                 else \
                     echo "error: do not know how to build OpenVPN $$openvpn_major_minor with '$$ssl_name'" ; \
                     exit 255 ; \
                 fi ; \
-                if [ "$$build_it" = true ] \
-                && [ -e "$$ssl_staging_dir" ] ; then \
+                if [ "$$build_it" = true ] ; then \
                     for a in $$target_archs ; do \
-                        echo "Making $$openvpn_name with $$ssl_name for $$a" ; \
-                        mwd="$$(pwd)" ; \
-                        $(MAKE) clean; \
-                        \
-                        if [ -f "$(OPENVPN_SOURCE_DIR)/$$openvpn_name/configure-options.txt" ] ; then \
-                            configure_options="$$(cat $(OPENVPN_SOURCE_DIR)/$$openvpn_name/configure-options.txt)" ; \
+                        if [ -e "$${ssl_staging_dir}_$$a" ] ; then \
+                            echo "Making $$openvpn_name with $$ssl_name for $$a" ; \
+                            \
+                            $(MAKE) clean; \
+                            \
+                            if [ -f "$(OPENVPN_SOURCE_DIR)/$$openvpn_name/configure-options.txt" ] ; then \
+                                configure_options="$$(cat $(OPENVPN_SOURCE_DIR)/$$openvpn_name/configure-options.txt)" ; \
+                            else \
+                                echo "error: configure-options.txt missing in $(OPENVPN_SOURCE_DIR)/$$openvpn_name" ; \
+                                exit 255 ; \
+                            fi ; \
+                            if [ "$${a:0:3}" = "arm" ] ; then \
+                                TB_CONFIGURE_BUILD="arm-apple-darwin" ; \
+                            else \
+                                TB_CONFIGURE_BUILD="$$a-apple-darwin" ; \
+                            fi ; \
+                            \
+                            \
+                            \
+                            if [ -n "$$pkcs11_enable" ] ; then \
+                                CC="$(CC)" \
+                                    CFLAGS="$(CFLAGS) -arch $$a $(OPENVPN_DEPRECATED_LLVN_OPTION) -D __APPLE_USE_RFC_3542" \
+                                    LZO_CFLAGS="-I$(LZO_STAGING_DIR)_$$a/include" \
+                                    LZO_LIBS="-L$(LZO_STAGING_DIR)_$$a/lib -llzo2" \
+                                    LZ4_CFLAGS="-I$(LZ4_STAGING_DIR)_$$a/include" \
+                                    LZ4_LIBS="-L$(LZ4_STAGING_DIR)_$$a/lib -llz4" \
+                                    OPENSSL_CFLAGS="-I$${ssl_staging_dir}_$$a/include" \
+                                    OPENSSL_SSL_CFLAGS="-I$${ssl_staging_dir}_$$a/include" \
+                                    OPENSSL_CRYPTO_CFLAGS="-I$${ssl_staging_dir}_$$a/include" \
+                                    OPENSSL_LIBS="$${ssl_staging_dir}_$$a/lib/libssl.a -lz $${ssl_staging_dir}_$$a/lib/libcrypto.a -lz" \
+                                    OPENSSL_SSL_LIBS="$${ssl_staging_dir}_$$a/lib/libssl.a" \
+                                    OPENSSL_CRYPTO_LIBS="$${ssl_staging_dir}_$$a/lib/libcrypto.a -lz" \
+                                    PKCS11_HELPER_CFLAGS="-I$(PKCS11_STAGING_DIR)_$$a/include/" \
+                                    PKCS11_HELPER_LIBS="-L$(PKCS11_STAGING_DIR)_$$a/lib -lpkcs11-helper" \
+                                    OS_VERSION=$$(uname -r) \
+                                    ./configure \
+                                        --build="$$TB_CONFIGURE_BUILD" \
+                                        --host="$(TB_CONFIGURE_HOST)" \
+                                        $$pkcs11_enable \
+                                        $$configure_options ; \
+                                \
+                                $(MAKE) $(OPENVPN_DEPRECATED_GCC_MAKE_OPTION) ; \
+                            else \
+                                CC="$(CC)" \
+                                    CFLAGS="$(CFLAGS) -arch $$a $(OPENVPN_DEPRECATED_LLVN_OPTION) -D __APPLE_USE_RFC_3542" \
+                                    LZO_CFLAGS="-I$(LZO_STAGING_DIR)_$$a/include" \
+                                    LZO_LIBS="-L$(LZO_STAGING_DIR)_$$a/lib -llzo2" \
+                                    LZ4_CFLAGS="-I$(LZ4_STAGING_DIR)_$$a/include" \
+                                    LZ4_LIBS="-L$(LZ4_STAGING_DIR)_$$a/lib -llz4" \
+                                    OPENSSL_CFLAGS="-I$${ssl_staging_dir}_$$a/include" \
+                                    OPENSSL_SSL_CFLAGS="-I$${ssl_staging_dir}_$$a/include" \
+                                    OPENSSL_CRYPTO_CFLAGS="-I$${ssl_staging_dir}_$$a/include" \
+                                    OPENSSL_LIBS="$${ssl_staging_dir}_$$a/lib/libssl.a -lz $${ssl_staging_dir}_$$a/lib/libcrypto.a -lz" \
+                                    OPENSSL_SSL_LIBS="$${ssl_staging_dir}_$$a/lib/libssl.a" \
+                                    OPENSSL_CRYPTO_LIBS="$${ssl_staging_dir}_$$a/lib/libcrypto.a -lz" \
+                                    OS_VERSION=$$(uname -r) \
+                                    ./configure \
+                                        --build="$$TB_CONFIGURE_BUILD" \
+                                        --host="$(TB_CONFIGURE_HOST)" \
+                                        $$pkcs11_enable \
+                                        $$configure_options ; \
+                                \
+                                $(MAKE) $(OPENVPN_DEPRECATED_GCC_MAKE_OPTION) ; \
+                            fi ; \
+                            \
+                            echo "Making down-root plugin for $$a" ; \
+                            $(MAKE) -C src/plugins/down-root clean ; \
+                            $(MAKE) LDFLAGS="-bundle \
+                                             -Wl,-dylib_install_name,openvpn-down-root.so" \
+                                             -C src/plugins/down-root ; \
+                            if [ -e src/openvpn/openvpn ] ; then \
+                                cp -f -p -R src/openvpn/openvpn ../openvpn_tblk_$$a; \
+                            else \
+                                echo "warning: No file at $$(pwd)/src/openvpn/openvpn" ; \
+                            fi ; \
+                            if [ -e src/plugins/down-root/.libs/openvpn-plugin-down-root.so ] ; then \
+                                cp -f -p -R src/plugins/down-root/.libs/openvpn-plugin-down-root.so ../openvpn-plugin-down-root.so_tblk_$$a; \
+                            else \
+                                echo "warning: No file at $$(pwd)/src/plugins/down-root/.libs/openvpn-plugin-down-root.so" ; \
+                            fi ; \
+                            echo "Finished making down-root plugin for $$a" ; \
                         else \
-                            echo "error: configure-options.txt missing in $(OPENVPN_SOURCE_DIR)/$$openvpn_name" ; \
-                            exit 255 ; \
+                            echo "Not making $$openvpn_name with $$ssl_name because $$ssl_name is not available with architecture $$a (even though $$a is in the corresponding _TARGET_ARCHS make variable in third_party/Makefile)"; \
                         fi ; \
-                        \
-                        mwd="$$(pwd)" ; \
-                        CC="$(CC)" \
-                            CFLAGS="$(CFLAGS) \
-                                    -arch $$a \
-                                    $(OPENVPN_DEPRECATED_LLVN_OPTION) \
-                                    -D __APPLE_USE_RFC_3542" \
-                            LZO_CFLAGS="-I$(LZO_STAGING_DIR)/include" \
-                            LZO_LIBS="-L$(LZO_STAGING_DIR)/lib \
-                                      -llzo2" \
-                            LZ4_CFLAGS="-I$(LZ4_STAGING_DIR)/include" \
-                            LZ4_LIBS="-L$(LZ4_STAGING_DIR)/lib \
-                                      -llz4" \
-                            OPENSSL_CFLAGS="-I$${ssl_staging_dir}/$$a/include" \
-                            OPENSSL_SSL_CFLAGS="-I$${ssl_staging_dir}/$$a/include" \
-                            OPENSSL_CRYPTO_CFLAGS="-I$${ssl_staging_dir}/$$a/include" \
-                            OPENSSL_LIBS="$${ssl_staging_dir}/lib/libssl.a -lz $${ssl_staging_dir}/lib/libcrypto.a -lz" \
-                            OPENSSL_SSL_LIBS="$${ssl_staging_dir}/lib/libssl.a" \
-                            OPENSSL_CRYPTO_LIBS="$${ssl_staging_dir}/lib/libcrypto.a -lz" \
-                            PKCS11_HELPER_CFLAGS="-I$(PKCS11_STAGING_DIR)/include/" \
-                            PKCS11_HELPER_LIBS="-L$(PKCS11_STAGING_DIR)/lib \
-                                                -lpkcs11-helper" \
-                            OS_VERSION=$$(uname -r) \
-                            autoreconf -i -v; \
-                        \
-                        mwd="$$(pwd)" ; \
-                        case "$$a" in \
-                         arm64) BUILD_STR="arm-apple-darwin" ;; \
-                             *) BUILD_STR="$$a-apple-darwin" ;; \
-                        esac ; \
-                        CC="$(CC)" \
-                            CFLAGS="$(CFLAGS) \
-                                    -arch $$a \
-                                    $(OPENVPN_DEPRECATED_LLVN_OPTION) \
-                                    -D __APPLE_USE_RFC_3542" \
-                            LZO_CFLAGS="-I$(LZO_STAGING_DIR)/include" \
-                            LZO_LIBS="-L$(LZO_STAGING_DIR)/lib \
-                                      -llzo2" \
-                            LZ4_CFLAGS="-I$(LZ4_STAGING_DIR)/include" \
-                            LZ4_LIBS="-L$(LZ4_STAGING_DIR)/lib \
-                                      -llz4" \
-                            OPENSSL_CFLAGS="-I$${ssl_staging_dir}/$$a/include" \
-                            OPENSSL_SSL_CFLAGS="-I$${ssl_staging_dir}/$$a/include" \
-                            OPENSSL_CRYPTO_CFLAGS="-I$${ssl_staging_dir}/$$a/include" \
-                            OPENSSL_LIBS="$${ssl_staging_dir}/lib/libssl.a -lz $${ssl_staging_dir}/lib/libcrypto.a -lz" \
-                            OPENSSL_SSL_LIBS="$${ssl_staging_dir}/lib/libssl.a" \
-                            OPENSSL_CRYPTO_LIBS="$${ssl_staging_dir}/lib/libcrypto.a -lz" \
-                            PKCS11_HELPER_CFLAGS="-I$(PKCS11_STAGING_DIR)/include/" \
-                            PKCS11_HELPER_LIBS="-L$(PKCS11_STAGING_DIR)/lib \
-                                                -lpkcs11-helper" \
-                            OS_VERSION=$$(uname -r) \
-                            ./configure \
-                                --build=$$BUILD_STR \
-                                $$pkcs11_enable \
-                                $$configure_options ; \
-                        \
-                        $(MAKE) LIBS="$$ssl_target_files \
-                                      -L$(PKCS11_STAGING_DIR)/lib \
-                                      -L$(LZO_STAGING_DIR)/lib \
-                                      -L$(LZ4_STAGING_DIR)/lib \
-                                      -lpkcs11-helper \
-                                      -llzo2 \
-                                      -llz4" \
-                                      $(OPENVPN_DEPRECATED_GCC_MAKE_OPTION) ; \
-                        \
-                        echo "Making down-root plugin for $$a" ; \
-                        $(MAKE) -C src/plugins/down-root clean ; \
-                        $(MAKE) LDFLAGS="-bundle \
-                                         -Wl,-dylib_install_name,openvpn-down-root.so" \
-                                         -C src/plugins/down-root ; \
-                        if [ -e src/openvpn/openvpn ] ; then \
-                            cp -f -p -R src/openvpn/openvpn ../openvpn_tblk_$$a; \
-                        else \
-                            echo "warning: No file at $$mwd/src/openvpn/openvpn" ; \
-                        fi ; \
-                        if [ -e src/plugins/down-root/.libs/openvpn-plugin-down-root.so ] ; then \
-                            cp -f -p -R src/plugins/down-root/.libs/openvpn-plugin-down-root.so ../openvpn-plugin-down-root.so_tblk_$$a; \
-                        else \
-                            echo "warning: No file at $$mwd/src/plugins/down-root/.libs/openvpn-plugin-down-root.so" ; \
-                        fi ; \
-                        echo "Finished making down-root plugin for $$a" ; \
                     done; \
                     mkdir -p "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name" ; \
-                    lipo ../openvpn-plugin-down-root.so_tblk_* -create -output "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-down-root.so"; \
-                    cd ../; \
-                    lipo openvpn_tblk_* -create -output "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-executable"; \
-                    if [   ! -e "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-executable" \
-                        -o ! -e "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-down-root.so" ] ; then \
-                        cd openvpn ; \
+                    \
+                    if [ "$${target_archs/ /}" = "$$target_archs" ] ; then \
+                        echo "warning: $$openvpn_name with $$ssl_name is not Universal, its only for $$target_archs" ; \
+                        cp -af ../openvpn_tblk_$$target_archs                     "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-executable"; \
+                        cp -af ../openvpn-plugin-down-root.so_tblk_$$target_archs "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-down-root.so"; \
+                    else \
+                        echo "info: $$openvpn_name with $$ssl_name is Universal ($$target_archs)" ; \
+                        lipo ../openvpn_tblk_* -create -output                      "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-executable"; \
+                        lipo ../openvpn-plugin-down-root.so_tblk_* -create -output "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-down-root.so"; \
+                    fi ; \
+                    \
+                    missing_a_component="false" ; \
+                    if [   ! -e "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-executable" ] ; then \
+                        echo "No $$openvpn_name-$$ssl_name/openvpn-executable" ; \
+                        missing_a_component="true" ; \
+                    fi ; \
+                    if [   ! -e "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name/openvpn-down-root.so" ] ; then \
+                        echo "No $$openvpn_name-$$ssl_name/openvpn-down-root.so" ; \
+                        missing_a_component="true" ; \
+                    fi ; \
+                    if "$$missing_a_component" ; then \
                         rm -f -R "$(OPENVPN_PRODUCTS_DIR)/$$openvpn_name-$$ssl_name" ; \
                         echo "error: removed $$openvpn_name-$$ssl_name folder because it did not contain both openvpn-executable and openvpn-down-root.so" ; \
                         exit 255; \
                     fi ; \
-                    cd openvpn ; \
+                    \
+                    echo "Finished making $$openvpn_name with $$ssl_name (Architectures: $$target_archs)" ; \
                 else \
-                    if [ "$$build_it" != true ] ; then \
-                        echo "Not making $$openvpn_name with $$ssl_name because they are not compatible"; \
-                    fi ; \
-                    if [ ! -e "$$ssl_staging_dir" ] ; then \
-                        echo "Not making $$openvpn_name with $$ssl_name because $$ssl_name is not available"; \
-                    fi ; \
+                    echo "Not making $$openvpn_name with $$ssl_name because they are not compatible"; \
                 fi ; \
             done; \
         fi ; \
diff --git a/third_party/makefiles/Makefile-tuntap b/third_party/makefiles/Makefile-tuntap
--- a/third_party/makefiles/Makefile-tuntap
+++ b/third_party/makefiles/Makefile-tuntap
@@ -1,7 +1,7 @@
 # Makefile to build tuntap for Tunnelblick
 #
 # Copyright 2004, 2005, 2006, 2007, 2008, 2009 Angelo Laub
-# Contributions by Jonathan K. Bullard Copyright 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2020. All rights reserved.
+# Contributions by Jonathan K. Bullard Copyright 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2020, 2021. All rights reserved.
 #
 #  This file is part of Tunnelblick.
 #
@@ -28,58 +28,56 @@ built-tuntap-prepare:
 	&&   [ ! -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] ; then \
 		echo "error: THIRD_PARTY: If tun-notarized.kext is present in the third_party folder, tap-notarized.kext must also be present" ; \
 		exit 1 ; \
-    fi ; \
+	fi ; \
 	\
-    echo "THIRD_PARTY: Expanding Tun/Tap ..." ; \
-    cd $(TUNTAP_SOURCE_DIR)/$(TUNTAP_CURRENT_NAME) ; \
+	echo "THIRD_PARTY: Expanding Tun/Tap ..." ; \
+	cd $(TUNTAP_SOURCE_DIR)/$(TUNTAP_CURRENT_NAME) ; \
 	mkdir -p $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME) ; \
 	tar -x -f $(TUNTAP_CURRENT_TARGZ) -C $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME) ; \
 	echo "THIRD_PARTY: Patching Tun/Tap.." ; \
-    if [ -d $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME)/tuntap ] ; then \
-        cd $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME)/tuntap ; \
-        for patch_file in $(TUNTAP_SOURCE_DIR)/$(TUNTAP_CURRENT_NAME)/patches/*.diff; do \
-            patch_name=$(TUNTAP_CURRENT_NAME)/$$(basename "$${patch_file}") ; \
-            patch -p0 -N --dry-run -i $$patch_file > /dev/null; \
-            if [ $$? == 0 ]; then \
-                patch -p0 -N -i $$patch_file; \
-                if [ $$? == 0 ]; then \
-                    echo "Tun/Tap patch applied: $$patch_name" ; \
-                else \
-                    echo "error: Tun/Tap patch failed after a successful dry run: $$patch_name" ; \
-                fi \
-            else \
-                echo "error: Tun/Tap patch could not be applied: $$patch_name" ; \
-            fi \
-        done ; \
-    fi ; \
-    echo "THIRD_PARTY: Patched Tun/Tap" ; \
+	if [ -d $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME)/tuntap ] ; then \
+		cd $(TUNTAP_BUILD_DIR)/$(TUNTAP_CURRENT_NAME)/tuntap ; \
+		for patch_file in $(TUNTAP_SOURCE_DIR)/$(TUNTAP_CURRENT_NAME)/patches/*.diff; do \
+			patch_name=$(TUNTAP_CURRENT_NAME)/$$(basename "$${patch_file}") ; \
+			patch -p0 -N --dry-run -i $$patch_file > /dev/null; \
+			if [ $$? == 0 ]; then \
+				patch -p0 -N -i $$patch_file; \
+				if [ $$? == 0 ]; then \
+					echo "Tun/Tap patch applied: $$patch_name" ; \
+				else \
+					echo "error: Tun/Tap patch failed after a successful dry run: $$patch_name" ; \
+				fi \
+ 			else \
+				echo "error: Tun/Tap patch could not be applied: $$patch_name" ; \
+				patch -p0 -N --dry-run -i $$patch_file ; \
+			fi ; \
+		done ; \
+	fi ; \
+	echo "THIRD_PARTY: Patched Tun/Tap" ; \
 	touch $(TOPDIR)/built-tuntap-prepare
 
 built-tuntap: built-tuntap-prepare
-	if [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] \
-	&& [ ! -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
-		echo "error: THIRD_PARTY: If tap-notarized.kext is present in the third_party folder, tun-notarized.kext must also be present" ; \
-		exit 1 ; \
-	fi ; \
-	if [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] \
-	&&   [ ! -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] ; then \
-		echo "error: THIRD_PARTY: If tun-notarized.kext is present in the third_party folder, tap-notarized.kext must also be present" ; \
-		exit 1 ; \
-	fi ; \
-	\
-	echo "THIRD_PARTY: Copying pre-build notarized kexts" ; \
 	mkdir -p $(TUNTAP_PRODUCTS_DIR) ; \
-	cp -f -a $(TUNTAP_PREBUILT_TAP_NOTARIZED) $(TUNTAP_PRODUCTS_DIR)/tap-notarized.kext ; \
-	cp -f -a $(TUNTAP_PREBUILT_TUN_NOTARIZED) $(TUNTAP_PRODUCTS_DIR)/tun-notarized.kext ; \
+	if [ -e $(TUNTAP_PREBUILT_TAP_NOTARIZED) ] ; then \
+		echo "THIRD_PARTY: Copying pre-built notarized tap kext" ; \
+		cp -f -a $(TUNTAP_PREBUILT_TAP_NOTARIZED) $(TUNTAP_PRODUCTS_DIR)/tap-notarized.kext ; \
+	else \
+		echo "THIRD_PARTY: No pre-built notarized tun kext" ; \
+	fi ; \
+	if [ -e $(TUNTAP_PREBUILT_TUN_NOTARIZED) ] ; then \
+		echo "THIRD_PARTY: Copying pre-built notarized tun kext" ; \
+		cp -f -a $(TUNTAP_PREBUILT_TUN_NOTARIZED) $(TUNTAP_PRODUCTS_DIR)/tun-notarized.kext ; \
+	else \
+		echo "THIRD_PARTY: No pre-built notarized tun kext" ; \
+	fi ; \
 	\
-    echo "THIRD_PARTY: Building Tun/Tap for '$(ARCHS)' with deploy-target '$(MACOSX_DEPLOYMENT_TARGET)' and SDK path '$(SDK_DIR)'" ; \
-    export TUNTAP_ARCHS="$(foreach f, $(TUNTAP_TARGET_ARCHS), -arch $f)" ; \
-    cd $(TUNTAP_BUILD_DIR) ; \
-    mkdir -p $(TUNTAP_PRODUCTS_DIR) ; \
-    $(MAKE) -C $(TUNTAP_CURRENT_NAME)/tuntap/ ; \
-    cp -f -a $(TUNTAP_CURRENT_NAME)/tuntap/tap.kext $(TUNTAP_PRODUCTS_DIR)/tap.kext ; \
-    cp -f -a $(TUNTAP_CURRENT_NAME)/tuntap/tun.kext $(TUNTAP_PRODUCTS_DIR)/tun.kext ; \
-    echo "THIRD_PARTY: Built Tun/Tap" ; \
+	echo "THIRD_PARTY: Building Tun/Tap for '$(TUNTAP_TARGET_ARCHS)' ($(TUNTAP_ARCH_ARGS)) with deploy-target '$(MACOSX_DEPLOYMENT_TARGET)' and SDK path '$(SDK_DIR)'" ; \
+	cd $(TUNTAP_BUILD_DIR) ; \
+	mkdir -p $(TUNTAP_PRODUCTS_DIR) ; \
+	$(MAKE) -C $(TUNTAP_CURRENT_NAME)/tuntap/ TUNTAP_ARCH_ARGS=\"$(TUNTAP_ARCH_ARGS)\" ; \
+	cp -f -a $(TUNTAP_CURRENT_NAME)/tuntap/tap.kext $(TUNTAP_PRODUCTS_DIR)/tap.kext ; \
+	cp -f -a $(TUNTAP_CURRENT_NAME)/tuntap/tun.kext $(TUNTAP_PRODUCTS_DIR)/tun.kext ; \
+	echo "THIRD_PARTY: Built Tun/Tap" ; \
 	touch $(TOPDIR)/built-tuntap
 
 built-tuntap-clean:
