Build 2952: Yet another problem with whitespace in the easy-rsa path fixed.

diff --git a/third_party/openvpn/openvpn-2.2.1/patches/easy-rsa-fix-space-in-path.diff b/third_party/openvpn/openvpn-2.2.1/patches/easy-rsa-fix-space-in-path.diff
--- a/third_party/openvpn/openvpn-2.2.1/patches/easy-rsa-fix-space-in-path.diff
+++ b/third_party/openvpn/openvpn-2.2.1/patches/easy-rsa-fix-space-in-path.diff
@@ -26,3 +26,32 @@ Index: easy-rsa/2.0/vars
  
  # Edit this variable to point to
  # your soon-to-be-created key
+Index: easy-rsa/2.0/whichopensslcnf
+===================================================================
+--- easy-rsa/2.0/whichopensslcnf	(revision 1950)
++++ easy-rsa/2.0/whichopensslcnf	(working copy)
+@@ -3,20 +3,20 @@
+ cnf="$1/openssl.cnf"
+ 
+ if [ "$OPENSSL" ]; then
+-	if $OPENSSL version | grep -E "0\.9\.6[[:alnum:]]" > /dev/null; then
++	if "$OPENSSL" version | grep -E "0\.9\.6[[:alnum:]]" > /dev/null; then
+ 		cnf="$1/openssl-0.9.6.cnf"
+ 	elif $OPENSSL version | grep -E "0\.9\.8[[:alnum:]]" > /dev/null; then
+ 		cnf="$1/openssl-0.9.8.cnf"
+-	elif $OPENSSL version | grep -E "1\.0\.([[:digit:]][[:alnum:]])" > /dev/null; then
++	elif "$OPENSSL" version | grep -E "1\.0\.([[:digit:]][[:alnum:]])" > /dev/null; then
+                 cnf="$1/openssl-1.0.0.cnf"
+ 	else
+ 		cnf="$1/openssl.cnf"
+ 	fi
+ fi
+ 
+-echo $cnf
++echo "$cnf"
+ 
+-if [ ! -r $cnf ]; then
++if [ ! -r "$cnf" ]; then
+     echo "**************************************************************" >&2
+     echo "  No $cnf file could be found" >&2
+     echo "  Further invocations will fail" >&2
